export declare enum SocketEvents {
    CONNECT = "connect",
    DISCONNECT = "disconnect",
    JOIN_ROOM = "join_room",
    LEAVE_ROOM = "leave_room",
    USER_JOINED = "user_joined",
    USER_LEFT = "user_left",
    ROOM_STATE = "room_state",
    ROOM_STATE_UPDATE = "room_state_update",
    PLAY = "play",
    PAUSE = "pause",
    SEEK = "seek",
    SYNC_TIME = "sync_time",
    VIDEO_ENDED = "video_ended",
    ADD_TO_QUEUE = "add_to_queue",
    REMOVE_FROM_QUEUE = "remove_from_queue",
    SKIP_CURRENT = "skip_current",
    QUEUE_UPDATE = "queue_update",
    SEARCH_VIDEOS = "search_videos",
    SEARCH_RESULTS = "search_results",
    ERROR = "error"
}
