version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://server:4000
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - CLIENT_URL=http://client:3000
    volumes:
      - server_data:/app/data

volumes:
  server_data: 